spring:
  datasource:
    url: jdbc:mysql://localhost:3306/url
    username: KirarutoAdmin
    password: Kira22@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
      enabled: false
      locations: classpath:db/migration
    jpa:
      hibernate:
        ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
  port: 8081

logging:
  level:
    org.flywaydb.core: DEBUG

climaReal:
  api:
    key: 258d2cd81806ad54e581eefe0264b65d
    endpoint: https://api.openweathermap.org/data/2.5/weather

climaHistorical:
  api:
    key: VSAV69LEC5WW9GDJV6XU77DBX
    endpoint: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/


